### ISSUE TITLE
[iOS safari] The circle border of scoll indicator is clipped

### ISSUE THREAD

**Issue by fontofonto** [measurabledatatoken/mai-website#63]
**Problem**
The circle border of scoll indicator is clipped on iOS 13.3 safari 
![IMG_8EB6B38B2A03-1](https://user-images.githubusercontent.com/11145511/72720833-bfba5300-3bb5-11ea-9d3a-815f24ab8651.jpeg)

**Solution**
add a line of css `box-sizing: border-box;` to it

**Comment by mailtime-wing** [comment]
- iphone xs can reproduce ( ios 13.3 )
- iphone xs max cannot reproduce  ( ios 13.3 )

**Comment by fontofonto** [comment]
Tested on iOS safari dev tool
Solve the rendering problem by adding 0.05rem to width and height

width: 1.05rem;
height: 1.05rem;
border: solid 0.05rem white;

please check.
