### ISSUE TITLE
Data Insights preview thumbnail missing

### ISSUE THREAD

**Issue by Jellygoo** [measurabledatatoken/mai-website#79]
Data Insights preview thumbnail missing

<img width="775" alt="Screenshot 2020-02-20 at 2 45 34 PM" src="https://user-images.githubusercontent.com/61143588/74908057-c247dc80-53ef-11ea-9b29-3c9f76ddda62.png">

**Comment by mailtime-wing** [comment]
I close this because it solved after rebuild.
