### ISSUE TITLE
New Data Insight article not showing on landing page

### ISSUE THREAD

**Issue by Jellygoo** [measurabledatatoken/mai-website#80]
Charlie uploaded a new article to Data Insights last nite. I can see it when I'm inside Data Insights but it's not showing up on the website landing page.
<img width="1075" alt="Screenshot 2020-03-05 at 2 33 53 PM" src="https://user-images.githubusercontent.com/61143588/75954382-86803d00-5eee-11ea-945b-e4fde42511fd.png">
<img width="787" alt="Screenshot 2020-03-05 at 12 34 36 PM" src="https://user-images.githubusercontent.com/61143588/75954415-99930d00-5eee-11ea-8e1b-cc1b3f9429e9.png">

**Comment by chochihim** [comment]
I have just fixed it
